### ISSUE TITLE
Add in County Level Data

### ISSUE THREAD

**Issue by sonoshah** [AAPIData/stats#19]
Using the `county.rmd` file, update the code to import and display the topics to duplicate what we have on our old version of QuickStats.

Just making this an issue so we can keep track. 

- [x] AA + NHPI + State Pop (show Alone + Combo for AA + NHPI)
- [x] Detailed Origin AA (Alone + Combo)
- [x] Detailed Origin NHPI Alone + Combo)

## Topic Areas:
> Use the same groupings as state (i.e. major racial groups, asian detail alone, asian detail combo, etc.

- [x] Educational Attainment 
- [x] Health Insurance
- [x] Poverty
- [x] Nativity
- [x] LEP
- [x] CVAP (use same groupings as state)

**Comment by SunnyYShao** [comment]
finished county level data

**Comment by SunnyYShao** [comment]
all final table is in congressional level/ready4github (the documents with green light)
