### ISSUE TITLE
Add in Congressional District Data

### ISSUE THREAD

**Issue by sonoshah** [AAPIData/stats#21]
Using district template, add in all congressional district data to match existing tables on live site.

**Comment by SunnyYShao** [comment]
jan 14th Finalized all district level data

**Comment by sonoshah** [comment]
hey @SunnyYShao , I added in everything in the district data except for the CVAP stuff. Can you take a look at that? I'm not sure how you planned to display it? 

The latest district_working has loaded the district cvap but hasn't done anything else, just fyi
