### ISSUE TITLE
state_pop mapping value

### ISSUE THREAD

**Issue by SunnyYShao** [AAPIData/stats#4]
state_pop not mapped based on the value of total state population

state_pop_map <- state_pop_map %>%
  gather(estimate_type,
         estimate,
         -geodisplaylabel,
         -group_name,
         -group_id)

 state_pop_map <- state_pop_map %>%
     filter(group_name %in% groups_alone) %>%
   filter(str_detect(estimate_type, "est_tot")) %>%
     select(-group_id) %>%
     mutate(long_key=paste(group_name, estimate_type, sep="_")) %>% #Combining Pop_ID and Estimate type
     select(-group_name, -estimate_type)  %>% 
     spread(long_key, estimate,fill = NA) 
  

state_pop_map <- state_pop_map %>% mutate(
  state_pop = `Total population_est_tot_pop`/1000,
  asian_pop = `Asian alone_est_tot_pop`/1000,
  nhpi_pop = `NHPI alone_est_tot_pop`/1000)

x <- c("{point.name}:", "Asian Alone:","NHPI Alone:")
title<-"State Population"
y <- c(" {point.value:,.0f} thousand", " {point.asian_pop:,.0f} thousand",
" {point.nhpi_pop:,.0f} thousand")
#style <- "style=font-size:80%"

data(usgeojson)
highchart() %>%
  hc_title(text = "State Population", align = "center") %>%
  hc_subtitle(text = "Source: 2011-2015 ACS using Asian/NHPI Alone", align = "center") %>%
  hc_chart(backgroundColor = "transparent") %>%
  hc_add_series_map(usgeojson, state_pop_map, name = "State Population", value = "state_pop", joinBy = c("name", "geodisplaylabel"),
                    borderColor= "transparent") %>%
  hc_tooltip(pointFormat = tooltip_table(x,y,title), useHTML=T,  headerFormat= "")%>%
  hc_add_theme(hc_theme_538()) %>%
  hc_colorAxis(stops = color_stops(5),labels= list(format = "{value}"),showInLegend=T) %>%
  hc_legend(title = list(text= "Statewide Population", fontStyle ='italic'),align = "center",verticalAlign = "bottom",
            layout = "horizontal", padding = 5) %>% 
  #hc_legend(layout = "vertical", align = "right",
   #         floating = TRUE, valueDecimals = 0, valueSuffix = " thousand") 
  hc_exporting(enabled = TRUE)

**Comment by sonoshah** [comment]
Basically, I created a new State pop that was just divided by a million, then merged the data on that, then made styling changes so only state pop would be divided by a million, then added suffixes to state pop in the tooltip and the legend so people will know.
